/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.utn.gui;
import com.utn.logica.*;
import com.utn.utilidades.Archivos;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Anthony
 */
public class MenuPrincipal extends javax.swing.JFrame {
    ArrayList<Producto> listaProductos;
    ArrayList<Producto> listaCompra;
    ArrayList<Corporativo> clientesCorp;
    Archivos archivos;
    DefaultTableModel modelo;
    ArrayList<TipoTarjeta> tarjetas;
    /**
     * Creates new form MneuPrincipal
     */
    public MenuPrincipal() throws Exception {
        
        ArrayList<Producto> productos;
        
        //this.getContentPane().setBackground(new Color(255,255,255));
        initComponents();
       
        archivos=new Archivos();
        listaCompra=new ArrayList<Producto>();
        clientesCorp=new ArrayList<Corporativo>();
        
        instanciaTarjetas();
        llenarCombo();
        llenarClientesCorp();
        spDir.setVisible(false);
        lblDir.setVisible(false);
        cmbTarjetas.setVisible(false);
        
        
        String col[] = {"Codigo","Desc","Precio"};
        modelo = new DefaultTableModel(col,0);
        tblLista.setModel(modelo);
        
    }
    
    
    
    public void instanciaTarjetas(){
        TipoTarjeta visa = new TipoTarjeta("Visa");
        TipoTarjeta mastercard = new TipoTarjeta("Master card");
        TipoTarjeta americanexpress = new TipoTarjeta("American Express");
        tarjetas=new ArrayList<TipoTarjeta>();
        tarjetas.add(visa);
        tarjetas.add(mastercard);
        tarjetas.add(americanexpress);
    }
    
    public void llenarClientesCorp() throws Exception{
        clientesCorp=archivos.leerCorporativos();
        for (Corporativo cliente : clientesCorp) {
            cmbCliCorp.addItem(cliente.mostrarLista());
        }
    }
    
   
    
    public void llenarCombo() throws Exception{
        listaProductos=archivos.leerProductos();
        for(Producto producto:listaProductos){
            cmbProducto.addItem(producto.mostrarComboB());
        }
        
        for(TipoTarjeta tarjeta: tarjetas){
            cmbTarjetas.addItem(tarjeta.getDescripcion());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngCliente = new javax.swing.ButtonGroup();
        btngPago = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        cmbProducto = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        cmbTarjetas = new javax.swing.JComboBox<>();
        rbCorp = new javax.swing.JRadioButton();
        rbOca = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cmbCliCorp = new javax.swing.JComboBox<>();
        spDir = new javax.swing.JScrollPane();
        txtaDir = new javax.swing.JTextArea();
        bgContado = new javax.swing.JRadioButton();
        bgCredito = new javax.swing.JRadioButton();
        cmbMoneda = new javax.swing.JComboBox<>();
        lblDir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblLista);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");

        btngCliente.add(rbCorp);
        rbCorp.setSelected(true);
        rbCorp.setText("Corporativo");
        rbCorp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbCorpStateChanged(evt);
            }
        });
        rbCorp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCorpActionPerformed(evt);
            }
        });

        btngCliente.add(rbOca);
        rbOca.setText("Ocasional");

        jLabel1.setText("Tipo Cliente");

        txtaDir.setColumns(20);
        txtaDir.setRows(5);
        txtaDir.setToolTipText("Direccion");
        txtaDir.setAutoscrolls(false);
        spDir.setViewportView(txtaDir);

        btngPago.add(bgContado);
        bgContado.setSelected(true);
        bgContado.setText("Contado");
        bgContado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bgContadoStateChanged(evt);
            }
        });

        btngPago.add(bgCredito);
        bgCredito.setText("Credito");
        bgCredito.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bgCreditoStateChanged(evt);
            }
        });

        cmbMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colones", "Dolares" }));

        lblDir.setText("Direccion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bgContado)
                        .addGap(18, 18, 18)
                        .addComponent(cmbMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bgCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbTarjetas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbOca)
                            .addComponent(rbCorp)
                            .addComponent(cmbCliCorp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spDir, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(lblDir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbCorp)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCliCorp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(rbOca)
                        .addGap(35, 35, 35)
                        .addComponent(lblDir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spDir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bgContado)
                    .addComponent(bgCredito)
                    .addComponent(cmbMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseExited

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        listaCompra.add(listaProductos.get(cmbProducto.getSelectedIndex()));
        String codigo=listaProductos.get(cmbProducto.getSelectedIndex()).getCodigoProducto();
        String desc=listaProductos.get(cmbProducto.getSelectedIndex()).getDescripcion();
        String precio=listaProductos.get(cmbProducto.getSelectedIndex()).getCosto()+"";
        String prod[]={codigo,desc,precio};
        modelo.addRow(prod);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void rbCorpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbCorpStateChanged
        if(rbCorp.isSelected()){
            cmbCliCorp.setVisible(true);
            spDir.setVisible(false);
            lblDir.setVisible(false);
        }else{
            cmbCliCorp.setVisible(false);
            spDir.setVisible(true);
            lblDir.setVisible(true);
        }
    }//GEN-LAST:event_rbCorpStateChanged

    private void rbCorpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCorpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCorpActionPerformed

    private void bgCreditoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bgCreditoStateChanged
        if(bgCredito.isSelected()){
            cmbTarjetas.setVisible(true);
        }else{
            cmbTarjetas.setVisible(false);
        }
    }//GEN-LAST:event_bgCreditoStateChanged

    private void bgContadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bgContadoStateChanged
        if(bgContado.isSelected()){
            cmbMoneda.setVisible(true);
        }else{
            cmbMoneda.setVisible(false);
        }
    }//GEN-LAST:event_bgContadoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuPrincipal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bgContado;
    private javax.swing.JRadioButton bgCredito;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.ButtonGroup btngCliente;
    private javax.swing.ButtonGroup btngPago;
    private javax.swing.JComboBox<String> cmbCliCorp;
    private javax.swing.JComboBox<String> cmbMoneda;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JComboBox<String> cmbTarjetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDir;
    private javax.swing.JRadioButton rbCorp;
    private javax.swing.JRadioButton rbOca;
    private javax.swing.JScrollPane spDir;
    private javax.swing.JTable tblLista;
    private javax.swing.JTextArea txtaDir;
    // End of variables declaration//GEN-END:variables
}
